version: '3.8'

services:
  tailorx-db:
    image: postgres:latest
    container_name: tailorx-db
    environment:
      POSTGRES_PASSWORD: tailorx-db
      POSTGRES_DB: tailorx
    ports:
      - "5432:5432"
    volumes:
      - tailorx-data:/var/lib/postgresql/data

volumes:
  tailorx-data: